version = 0.1
[default.deploy.parameters]
stack_name = "cognito-dashboard"
resolve_s3 = true
s3_prefix = "cognito-dashboard"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
